name: AI Code Review  

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  id-token: write
  pull-requests: write
  repository-projects: write

jobs:
  ai_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Analyze Code with OpenAI
        run: |
          echo ${{ steps.checkout.outputs.code }}
          curl -X POST "https://api.openai.com/v1/chat/completions" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "model": "gpt-3.5-turbo",
                  "messages": [
                    {"role": "system", "content": "You are an AI code reviewer. Review the following code for quality, potential issues, and improvements."},
                    {"role": "user", "content": "${{ steps.checkout.outputs.code }}"}
                  ],
                  "temperature": 0.2,
                  "max_tokens": 1500
                }' > ai_review.json
          cat ai_review.json
      - name: Post AI Review as PR Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKENGITHUB }}
          script: |
            const fs = require('fs');
            const review = JSON.parse(fs.readFileSync('ai_review.json', 'utf8'));
            const comment = review.choices[0].text.trim();
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "### AI Code Review Bot 🤖\n" + comment
            });
